[Draft] Allow to send a list of files as argument
CodeNarc/CodeNarc pull request #717
Opened 2022-09-25 17:14 UTC by nvuillam

Fixes https://github.com/CodeNarc/CodeNarc/issues/714

2022-09-25 22:25 UTC, nvuillam commented
@chrismair i think we're (finally) good :)

2022-09-27 22:05 UTC, chrismair requested changes
Nice work. Looks promising.

2022-09-27 22:05 UTC, chrismair commented on src/main/groovy/org/codenarc/CodeNarc.groovy
> -        includes = includes  ?: '**/*.groovy'
Please add tests in CodeNarcTest for this new behavior.

2022-09-27 22:05 UTC, chrismair commented on src/main/groovy/org/codenarc/CodeNarc.groovy
> -        new FilesystemSourceAnalyzer(baseDirectory: baseDir, includes: includes, excludes: excludes, failOnError: failOnError)
Please add tests in CodeNarcTest for this new behavior.

2022-09-27 22:05 UTC, chrismair commented on src/main/groovy/org/codenarc/results/DirectoryResults.groovy
> +     */
Please add comprehensive tests to DirectoryResultsTest for this new method.

2022-09-27 22:05 UTC, chrismair commented on src/test/groovy/org/codenarc/analyzer/FilesSourceAnalyzerTest.groovy
> +
Add test for results with no violations?

2022-09-27 22:05 UTC, chrismair commented on src/main/groovy/org/codenarc/results/DirectoryResults.groovy
> +     */
Does this method need to be public?

2022-10-02 16:51 UTC, nvuillam commented on src/main/groovy/org/codenarc/CodeNarc.groovy
> -        includes = includes  ?: '**/*.groovy'
done :)

2022-10-02 16:51 UTC, nvuillam commented on src/main/groovy/org/codenarc/CodeNarc.groovy
> -        new FilesystemSourceAnalyzer(baseDirectory: baseDir, includes: includes, excludes: excludes, failOnError: failOnError)
done :)

2022-10-02 16:52 UTC, nvuillam commented on src/main/groovy/org/codenarc/results/DirectoryResults.groovy
> +     */
Done :)

2022-10-02 16:52 UTC, nvuillam commented on src/main/groovy/org/codenarc/results/DirectoryResults.groovy
> +     */
Set to private :)

2022-10-02 16:52 UTC, nvuillam commented on src/test/groovy/org/codenarc/analyzer/FilesSourceAnalyzerTest.groovy
> +
Done :)

2022-10-02 17:04 UTC, nvuillam commented
@chrismair it should be ok now :)

2022-10-08 13:45 UTC, merged

2022-10-08 13:45 UTC, chrismair commented
Thanks for the contribution!