Implement rule for missing asserts in spock
CodeNarc/CodeNarc pull request #728
Opened 2023-02-27 15:57 UTC by jean-andre-gauthier

# Summary
- Implements a rule that finds missing asserts in spock tests, based on [this comment](https://github.com/CodeNarc/CodeNarc/issues/261#issuecomment-498763705)
- The rule identifies boolean expressions in `if / for / switch / ...` blocks, where an explicit call to `assert` would be required
- The rule might produce false positives, as it relies on method names to determine whether an expression has a boolean type or not. This should happen rarely though: I have tested it on a large internal codebase (~500kloc Spock tests), and it produced only two false positives

# Checklist
- Implement the new Rule class. This is typically a subclass of AbstractAstVisitorRule. ✅ 
- Implement the associated Rule test class. This is typically a subclass of AbstractRuleTestCase. ✅ 
- Add the new rule class name to the appropriate RuleSet file under “src/main/resources/rulesets”. ✅ 
- Add the new rule description entries to “src/main/resources/codenarc-base-messages.properties”. This includes both “RuleName.description” and “RuleName.description.html” property entries. ✅ 
- Run LoadAllPredefinedRuleSetsTest. ✅ 
- Add a description of the new rule to the appropriate “src/main/site/apt/codenarc-rules-XX.apt” document. ✅ 
- Run the full CodeNarc test suite. This includes a test called RunCodeNarcAgainstProjectSourceCodeTest that runs CodeNarc against its own source code (including any code that you have added or changed). ✅

2023-03-02 15:47 UTC, leonard84 requested changes

2023-03-02 15:47 UTC, leonard84 commented on src/main/groovy/org/codenarc/rule/junit/SpockMissingAssertRule.groovy
> +            return block.statements.any(s -> s.getStatementLabels() != null && !s.getStatementLabels().isEmpty())
❔ Shouldn't this check if the label is in `SPOCK_LABELS`

2023-03-02 15:47 UTC, leonard84 commented on src/main/groovy/org/codenarc/rule/junit/SpockMissingAssertRule.groovy
> +        List<String> labels = statement.getStatementLabels()
In general, I would replace the usage of getters by properties, where possible.

2023-03-02 15:47 UTC, leonard84 commented on src/main/groovy/org/codenarc/rule/junit/SpockMissingAssertRule.groovy
> +        // Heuristic: assume that methods whose name matches BOOLEAN_METHOD_PATTERNS return a boolean
🧐 Actually, Spock treats any non-void method as an implicit assertion using Groovy-truth to evaluate the return value.

2023-03-02 15:47 UTC, leonard84 commented on src/test/groovy/org/codenarc/rule/junit/SpockMissingAssertRuleTest.groovy
> +                            false
I would keep it simple and start with tests that only focus on one thing for violations. Later on you can add include multiple things to check for accuracy.

2023-03-02 15:47 UTC, leonard84 commented on src/test/groovy/org/codenarc/rule/junit/SpockMissingAssertRuleTest.groovy
> +                        obj.method() !== obj.method()
You should test for `=~` and `==~` as well.

2023-03-02 15:47 UTC, leonard84 commented on src/test/groovy/org/codenarc/rule/junit/SpockMissingAssertRuleTest.groovy
> +                        then:
This is a false positive, as it is not a block that is recognized by Spock.

2023-03-02 15:47 UTC, leonard84 commented on src/main/groovy/org/codenarc/rule/junit/SpockMissingAssertRule.groovy
> +                currentLabel = spockLabels.last()
Spock only treats top-level labels as blocks, so you need to check that here.

2023-03-02 15:47 UTC, leonard84 commented on src/test/groovy/org/codenarc/rule/junit/SpockMissingAssertRuleTest.groovy
> +                    and:
Is there also a test that shows a violation in an `and` block?

2023-03-05 13:33 UTC, chrismair commented
Thanks Leonard for your review and comments.

2023-03-05 14:03 UTC, chrismair requested changes

2023-03-05 14:03 UTC, chrismair commented on build-groovy4.gradle
> +version = '3.2.1-groovy-4.0'
Since we are adding a new rule, this will likely be 3.3.0 (but I would not expect your PR to increment the version number, anyway)

2023-03-05 14:03 UTC, chrismair commented on docs/codenarc-rules-junit.md
> +*Since CodeNarc 3.2.1*
will likely be 3.3.0

2023-03-05 14:03 UTC, chrismair commented on docs/StarterRuleSet-AllRules.groovy.txt
> +    SpockMissingAssert
This is a generated file. No need to manually update it. Please remove from PR.

2023-03-05 14:03 UTC, chrismair commented on docs/StarterRuleSet-AllRulesByCategory.groovy.txt
> +    SpockMissingAssert
This is a generated file. No need to manually update it. Please remove from PR.

2023-03-05 14:03 UTC, chrismair commented on docs/codenarc-rule-index-by-name.md
> +  * [SpockMissingAssert](./codenarc-rules-junit.html#spockmissingassert-rule)
This is a generated file. No need to manually update it. Please remove from PR.

2023-03-05 14:03 UTC, chrismair commented on docs/codenarc-rule-index.md
> +  * [SpockMissingAssert](./codenarc-rules-junit.html#spockmissingassert-rule)
This is a generated file. No need to manually update it. Please remove from PR.

2023-03-05 14:03 UTC, chrismair commented on docs/codenarc-rules-junit.md
> +                true == false
Please add an inline comment at the end of the line where the rule violation occurs, e.g.
     `true == false    // violation`

2023-03-05 14:03 UTC, chrismair commented on docs/codenarc-rules-junit.md
> +                    true == false
Why does this test fail but the other passed? Might be worth an inline comment to explain that.

2023-03-05 14:03 UTC, chrismair commented on src/main/groovy/org/codenarc/rule/junit/SpockMissingAssertRule.groovy
> + * Copyright 2011 the original author or authors.
Update to 2023

2023-03-05 14:03 UTC, chrismair commented on src/main/groovy/org/codenarc/rule/junit/SpockMissingAssertRule.groovy
> +import org.codehaus.groovy.ast.stmt.*
Please expand instance imports to not use wildcards (not that it's wrong, just because it is the typical convention for the codebase)

2023-03-05 14:03 UTC, chrismair commented on src/test/groovy/org/codenarc/rule/junit/SpockMissingAssertRuleTest.groovy
> + * Copyright 2011 the original author or authors.
Update to 2023

2023-03-05 14:03 UTC, chrismair commented on src/main/groovy/org/codenarc/rule/junit/SpockMissingAssertRule.groovy
> +    int priority = 2
Change priority to 3 (since this is not checking for runtime errors)

2023-04-12 14:57 UTC, chrismair commented
@jean-andre-gauthier .. Thank you for this contribution .. are you intending to address Leonard's comments and my comments?

2023-04-12 17:58 UTC, jean-andre-gauthier commented
> @jean-andre-gauthier .. Thank you for this contribution .. are you intending to address Leonard's comments and my comments?

Hi @chrismair, thanks for your review, and apologies for keeping this PR open for so long. I’m abroad on holidays until 24.04, but I’ll address your and Leonard’s comments once I’m back, if that’s fine for you?

2023-04-14 13:51 UTC, chrismair commented
> > @jean-andre-gauthier .. Thank you for this contribution .. are you intending to address Leonard's comments and my comments?
> 
> Hi @chrismair, thanks for your review, and apologies for keeping this PR open for so long. I’m abroad on holidays until 24.04, but I’ll address your and Leonard’s comments once I’m back, if that’s fine for you?

Hmmm, a whole year?! Okay, we can revisit then.

2023-04-14 20:19 UTC, jean-andre-gauthier commented
> > > @jean-andre-gauthier .. Thank you for this contribution .. are you intending to address Leonard's comments and my comments?
> > 
> > 
> > Hi @chrismair, thanks for your review, and apologies for keeping this PR open for so long. I’m abroad on holidays until 24.04, but I’ll address your and Leonard’s comments once I’m back, if that’s fine for you?
> 
> Hmmm, a whole year?! Okay, we can revisit then.

I don’t have that many holidays unfortunately, I meant April 24th 2023 ;)

2023-04-16 17:08 UTC, chrismair commented
> > > > @jean-andre-gauthier .. Thank you for this contribution .. are you intending to address Leonard's comments and my comments?
> > > 
> > > 
> > > Hi @chrismair, thanks for your review, and apologies for keeping this PR open for so long. I’m abroad on holidays until 24.04, but I’ll address your and Leonard’s comments once I’m back, if that’s fine for you?
> > 
> > 
> > Hmmm, a whole year?! Okay, we can revisit then.
> 
> I don’t have that many holidays unfortunately, I meant April 24th 2023 ;)

Ha! Yes, Apr 24 of this year is much better!

2023-04-28 07:23 UTC, jean-andre-gauthier commented on src/main/groovy/org/codenarc/rule/junit/SpockMissingAssertRule.groovy
> +        List<String> labels = statement.getStatementLabels()
Replaced all getters I could find by properties

2023-04-28 08:26 UTC, jean-andre-gauthier commented on src/main/groovy/org/codenarc/rule/junit/SpockMissingAssertRule.groovy
> +                currentLabel = spockLabels.last()
I wasn't aware of that, thanks for pointing that out. I've added a check on `nNestedStatements == 0` (which has the effect of ignoring non-top-level labels), and added the test case `nonTopLevelLabels_MultipleViolations` to test the change.

2023-04-28 08:37 UTC, jean-andre-gauthier commented on src/test/groovy/org/codenarc/rule/junit/SpockMissingAssertRuleTest.groovy
> +                        then:
I have split this test into two (`nonTopLevelLabels_MultipleViolations` and `nestedClosureInCollectionLoops_SingleViolation`). With the fixes done [here](https://github.com/CodeNarc/CodeNarc/pull/728/files/49c3a1ceb0c148a428c032d8995299aa5546914b#r1123313819), it now reports the top-level label in the violation message, in case there are non-top-level labels (and ignores non-top-level labels in case there aren't any top-level labels)

2023-04-28 08:40 UTC, jean-andre-gauthier commented on src/test/groovy/org/codenarc/rule/junit/SpockMissingAssertRuleTest.groovy
> +                        obj.method() !== obj.method()
This is done in `booleanExpressionRegexOperators_MultipleViolations`

2023-04-28 14:36 UTC, jean-andre-gauthier commented on src/main/groovy/org/codenarc/rule/junit/SpockMissingAssertRule.groovy
> +            return block.statements.any(s -> s.getStatementLabels() != null && !s.getStatementLabels().isEmpty())
I have added a check on `SPOCK_LABELS`, and wrapped the `visit...` methods with a check that verifies that the class extends from `spock.lang.Specification`. Please let me know if that looks fine to you

2023-05-02 06:45 UTC, jean-andre-gauthier commented on src/test/groovy/org/codenarc/rule/junit/SpockMissingAssertRuleTest.groovy
> +                            false
Fair point, I've removed `"123" / 123 / def`, as that was already tested in statement_NoViolations

2023-05-02 06:46 UTC, jean-andre-gauthier commented on src/test/groovy/org/codenarc/rule/junit/SpockMissingAssertRuleTest.groovy
> +                    and:
Added an additional test `statementInAnd_SingleViolation` for that case

2023-05-02 07:34 UTC, jean-andre-gauthier commented on src/main/groovy/org/codenarc/rule/junit/SpockMissingAssertRule.groovy
> +        // Heuristic: assume that methods whose name matches BOOLEAN_METHOD_PATTERNS return a boolean
I unfortunately didn't find a way to check at the call site whether the invoked method is void or non-void. I suppose we could get that information at the definition site, but then we'd have to do a second pass on the AST. @chrismair, do you know if there's any alternative to that?

2023-05-28 17:22 UTC, chrismair commented on src/main/groovy/org/codenarc/rule/junit/SpockMissingAssertRule.groovy
> +        // Heuristic: assume that methods whose name matches BOOLEAN_METHOD_PATTERNS return a boolean
It is possible you could get that from a later compiler phase, but that would require some redesign of the rule to be an "enhanced classpath rule": [CodeNarc - About the Enhanced Classpath Rules](https://codenarc.org/codenarc-enhanced-classpath-rules.html). And would have implications on the required classpath, as noted there.

2023-05-29 17:56 UTC, chrismair approved these changes

2023-05-29 17:57 UTC, merged

2023-05-31 21:21 UTC, chrismair commented
Thanks for the contribution!